// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ofekatr/go-wire-practice/event"
)

// Injectors from wire.go:

func InitializeEvent(phrase string) (*event.Event, error) {
	message, err := event.NewMessage(phrase)
	if err != nil {
		return nil, err
	}
	greeter, err := event.NewGreeter(message)
	if err != nil {
		return nil, err
	}
	eventEvent, err := event.NewEvent(greeter)
	if err != nil {
		return nil, err
	}
	return eventEvent, nil
}
